// Initialize mockEmployees from localStorage or use default data
let mockEmployees = JSON.parse(localStorage.getItem("employees")) || [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    department: "HR",
    role: "Manager",
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    department: "Engineering",
    role: "Developer",
  },
  {
    id: 3,
    firstName: "Michael",
    lastName: "Brown",
    email: "michael.brown@example.com",
    department: "Marketing",
    role: "Executive",
  },
  {
    id: 4,
    firstName: "Emily",
    lastName: "Clark",
    email: "emily.clark@example.com",
    department: "Finance",
    role: "Analyst",
  },
  {
    id: 5,
    firstName: "Daniel",
    lastName: "Wilson",
    email: "daniel.wilson@example.com",
    department: "Sales",
    role: "Executive",
  },
  {
    id: 6,
    firstName: "Olivia",
    lastName: "Taylor",
    email: "olivia.taylor@example.com",
    department: "HR",
    role: "Coordinator",
  },
  {
    id: 7,
    firstName: "James",
    lastName: "Anderson",
    email: "james.anderson@example.com",
    department: "Engineering",
    role: "Team Lead",
  },
  {
    id: 8,
    firstName: "Sophia",
    lastName: "Thomas",
    email: "sophia.thomas@example.com",
    department: "Marketing",
    role: "Content Writer",
  },
  {
    id: 9,
    firstName: "William",
    lastName: "Moore",
    email: "william.moore@example.com",
    department: "Finance",
    role: "Accountant",
  },
  {
    id: 10,
    firstName: "Ava",
    lastName: "Martin",
    email: "ava.martin@example.com",
    department: "Sales",
    role: "Representative",
  },
  {
    id: 11,
    firstName: "Benjamin",
    lastName: "Lee",
    email: "benjamin.lee@example.com",
    department: "HR",
    role: "Recruiter",
  },
  {
    id: 12,
    firstName: "Charlotte",
    lastName: "Walker",
    email: "charlotte.walker@example.com",
    department: "Engineering",
    role: "Developer",
  },
  {
    id: 13,
    firstName: "Lucas",
    lastName: "Hall",
    email: "lucas.hall@example.com",
    department: "Marketing",
    role: "SEO Specialist",
  },
  {
    id: 14,
    firstName: "Mia",
    lastName: "Allen",
    email: "mia.allen@example.com",
    department: "Finance",
    role: "Analyst",
  },
  {
    id: 15,
    firstName: "Henry",
    lastName: "Young",
    email: "henry.young@example.com",
    department: "Sales",
    role: "Manager",
  },
  {
    id: 16,
    firstName: "Amelia",
    lastName: "Hernandez",
    email: "amelia.hernandez@example.com",
    department: "HR",
    role: "Assistant",
  },
  {
    id: 17,
    firstName: "Ethan",
    lastName: "King",
    email: "ethan.king@example.com",
    department: "Engineering",
    role: "Intern",
  },
  {
    id: 18,
    firstName: "Harper",
    lastName: "Wright",
    email: "harper.wright@example.com",
    department: "Marketing",
    role: "Designer",
  },
  {
    id: 19,
    firstName: "Alexander",
    lastName: "Lopez",
    email: "alexander.lopez@example.com",
    department: "Finance",
    role: "Accountant",
  },
  {
    id: 20,
    firstName: "Evelyn",
    lastName: "Hill",
    email: "evelyn.hill@example.com",
    department: "Sales",
    role: "Representative",
  },
  {
    id: 21,
    firstName: "Logan",
    lastName: "Scott",
    email: "logan.scott@example.com",
    department: "HR",
    role: "Recruiter",
  },
  {
    id: 22,
    firstName: "Abigail",
    lastName: "Green",
    email: "abigail.green@example.com",
    department: "Engineering",
    role: "Developer",
  },
  {
    id: 23,
    firstName: "Sebastian",
    lastName: "Adams",
    email: "sebastian.adams@example.com",
    department: "Marketing",
    role: "Executive",
  },
  {
    id: 24,
    firstName: "Emily",
    lastName: "Baker",
    email: "emily.baker@example.com",
    department: "Finance",
    role: "Analyst",
  },
  {
    id: 25,
    firstName: "Jack",
    lastName: "Nelson",
    email: "jack.nelson@example.com",
    department: "Sales",
    role: "Executive",
  },
  {
    id: 26,
    firstName: "Ella",
    lastName: "Carter",
    email: "ella.carter@example.com",
    department: "HR",
    role: "Manager",
  },
  {
    id: 27,
    firstName: "Aiden",
    lastName: "Mitchell",
    email: "aiden.mitchell@example.com",
    department: "Engineering",
    role: "QA",
  },
  {
    id: 28,
    firstName: "Scarlett",
    lastName: "Perez",
    email: "scarlett.perez@example.com",
    department: "Marketing",
    role: "Executive",
  },
  {
    id: 29,
    firstName: "Mateo",
    lastName: "Roberts",
    email: "mateo.roberts@example.com",
    department: "Finance",
    role: "Analyst",
  },
  {
    id: 30,
    firstName: "Grace",
    lastName: "Turner",
    email: "grace.turner@example.com",
    department: "Sales",
    role: "Coordinator",
  },
  {
    id: 31,
    firstName: "David",
    lastName: "Phillips",
    email: "david.phillips@example.com",
    department: "HR",
    role: "HR Executive",
  },
  {
    id: 32,
    firstName: "Chloe",
    lastName: "Campbell",
    email: "chloe.campbell@example.com",
    department: "Engineering",
    role: "DevOps Engineer",
  },
  {
    id: 33,
    firstName: "Joseph",
    lastName: "Parker",
    email: "joseph.parker@example.com",
    department: "Marketing",
    role: "Brand Manager",
  },
  {
    id: 34,
    firstName: "Zoey",
    lastName: "Evans",
    email: "zoey.evans@example.com",
    department: "Finance",
    role: "Intern",
  },
  {
    id: 35,
    firstName: "Samuel",
    lastName: "Edwards",
    email: "samuel.edwards@example.com",
    department: "Sales",
    role: "Executive",
  },
  {
    id: 36,
    firstName: "Lily",
    lastName: "Collins",
    email: "lily.collins@example.com",
    department: "HR",
    role: "Coordinator",
  },
  {
    id: 37,
    firstName: "Owen",
    lastName: "Stewart",
    email: "owen.stewart@example.com",
    department: "Engineering",
    role: "Developer",
  },
  {
    id: 38,
    firstName: "Hannah",
    lastName: "Sanchez",
    email: "hannah.sanchez@example.com",
    department: "Marketing",
    role: "Executive",
  },
  {
    id: 39,
    firstName: "Wyatt",
    lastName: "Morris",
    email: "wyatt.morris@example.com",
    department: "Finance",
    role: "Accountant",
  },
  {
    id: 40,
    firstName: "Aria",
    lastName: "Rogers",
    email: "aria.rogers@example.com",
    department: "Sales",
    role: "Manager",
  },
  {
    id: 41,
    firstName: "Luke",
    lastName: "Reed",
    email: "luke.reed@example.com",
    department: "HR",
    role: "Assistant",
  },
  {
    id: 42,
    firstName: "Layla",
    lastName: "Cook",
    email: "layla.cook@example.com",
    department: "Engineering",
    role: "Developer",
  },
  {
    id: 43,
    firstName: "Gabriel",
    lastName: "Morgan",
    email: "gabriel.morgan@example.com",
    department: "Marketing",
    role: "Social Media Executive",
  },
  {
    id: 44,
    firstName: "Nora",
    lastName: "Bell",
    email: "nora.bell@example.com",
    department: "Finance",
    role: "Analyst",
  },
  {
    id: 45,
    firstName: "Carter",
    lastName: "Murphy",
    email: "carter.murphy@example.com",
    department: "Sales",
    role: "Executive",
  },
  {
    id: 46,
    firstName: "Zoey",
    lastName: "Rivera",
    email: "zoey.rivera@example.com",
    department: "HR",
    role: "Recruiter",
  },
  {
    id: 47,
    firstName: "Elijah",
    lastName: "Cooper",
    email: "elijah.cooper@example.com",
    department: "Engineering",
    role: "Tech Lead",
  },
  {
    id: 48,
    firstName: "Penelope",
    lastName: "Richardson",
    email: "penelope.richardson@example.com",
    department: "Marketing",
    role: "Executive",
  },
  {
    id: 49,
    firstName: "Liam",
    lastName: "Bailey",
    email: "liam.bailey@example.com",
    department: "Finance",
    role: "Manager",
  },
  {
    id: 50,
    firstName: "Victoria",
    lastName: "Gray",
    email: "victoria.gray@example.com",
    department: "Sales",
    role: "Coordinator",
  }
];


// Function to save employees to localStorage
function saveEmployees() {
  localStorage.setItem("employees", JSON.stringify(mockEmployees));
}